# Generated by Django 5.1.6 on 2025-03-06 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credittransaction',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
